# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import owr_pb2 as owr__pb2


class OwrStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.receive_message = channel.unary_unary(
                '/owr.Owr/receive_message',
                request_serializer=owr__pb2.owr_request.SerializeToString,
                response_deserializer=owr__pb2.owr_response.FromString,
                )
        self.receive_alive_message = channel.unary_unary(
                '/owr.Owr/receive_alive_message',
                request_serializer=owr__pb2.alive_request.SerializeToString,
                response_deserializer=owr__pb2.alive_response.FromString,
                )


class OwrServicer(object):
    """Missing associated documentation comment in .proto file."""

    def receive_message(self, request, context):
        """Function invoked to send the request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def receive_alive_message(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OwrServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'receive_message': grpc.unary_unary_rpc_method_handler(
                    servicer.receive_message,
                    request_deserializer=owr__pb2.owr_request.FromString,
                    response_serializer=owr__pb2.owr_response.SerializeToString,
            ),
            'receive_alive_message': grpc.unary_unary_rpc_method_handler(
                    servicer.receive_alive_message,
                    request_deserializer=owr__pb2.alive_request.FromString,
                    response_serializer=owr__pb2.alive_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'owr.Owr', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Owr(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def receive_message(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/owr.Owr/receive_message',
            owr__pb2.owr_request.SerializeToString,
            owr__pb2.owr_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def receive_alive_message(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/owr.Owr/receive_alive_message',
            owr__pb2.alive_request.SerializeToString,
            owr__pb2.alive_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
